name: Serverless Deployement

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache Primes
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-
        
    - name: Set dependencies
      if: steps.cache-primes.outputs.cache-hit != 'true'
      uses: actions/setup-node@v1
    - run: npm ci 
    
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_MFA_KEY: ${{ secrets.AWS_MFA_KEY }}
        AWS_MFA_SERIAL_NUMBER: ${{ secrets.AWS_MFA_SERIAL_NUMBER }}
        AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
